In [110]:
import os

os.chdir(r"C:\Users\DELL\Desktop\apexplanet-data-analytics")

print(os.getcwd())

C:\Users\DELL\Desktop\apexplanet-data-analytics

In [111]:
print(os.listdir("data"))
print(os.listdir("data/processed"))

['ecommerce_sales.db', 'processed', 'raw']
['ecommerce_sales_34500.csv', 'ecommerce_sales_cleaned.csv']

In [112]:
import os

print(os.getcwd())
print(os.listdir("data"))
print(os.listdir("data/processed"))

C:\Users\DELL\Desktop\apexplanet-data-analytics
['ecommerce_sales.db', 'processed', 'raw']
['ecommerce_sales_34500.csv', 'ecommerce_sales_cleaned.csv']

In [113]:
import pandas as pd
from sqlalchemy import create_engine

# Load cleaned dataset
df = pd.read_csv("data/processed/ecommerce_sales_cleaned.csv")

# Create SQLite database
engine = create_engine("sqlite:///data/ecommerce_sales.db")

# Import dataset into SQLite
df.to_sql("ecommerce_sales", engine, if_exists="replace", index=False)

print("Database created successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Database created successfully!
Rows: 4851
Columns: 17

In [114]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("sqlite:///data/ecommerce_sales.db")

query = """
SELECT *
FROM ecommerce_sales
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1.0,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1.0,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1.0,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1.0,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1.0,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male
5,O100005,C15191,P214062,Beauty,53.91,0.10,2.0,Credit Card,2024-04-14,5,South,No,97.04,6.32,37.35,35,Female
6,O100006,C13772,P201363,Electronics,266.50,0.00,1.0,PayPal,2025-05-20,5,East,No,266.50,9.10,22.88,49,Male
7,O100007,C13092,P216691,Beauty,9.98,0.00,1.0,Credit Card,2023-09-14,4,West,No,9.98,4.51,-0.02,66,Other
8,O100008,C15734,P202751,Fashion,6.61,0.05,1.0,Debit Card,2023-10-23,6,West,No,6.28,3.43,-1.23,37,Female
9,O100009,C16265,P207782,Grocery,10.91,0.00,1.0,Credit Card,2023-10-31,6,South,No,10.91,2.76,-1.89,56,Male

In [115]:
import sqlite3
import pandas as pd

# Create/connect to SQLite database
conn = sqlite3.connect("ecommerce_sales.db")

print("Database connected successfully!")

Database connected successfully!

In [116]:
df.to_sql("ecommerce_sales", conn, if_exists="replace", index=False)

print("Data imported into SQLite successfully!")

Data imported into SQLite successfully!

In [117]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current folder:
C:\Users\DELL\Desktop\apexplanet-data-analytics

Files/folders here:
['.git', 'dashboards', 'data', 'ecommerce_sales.db', 'notebooks', 'reports', 'scripts', 'sql']

In [118]:
import pandas as pd

df = pd.read_csv("data/processed/ecommerce_sales_cleaned.csv")

print(df.shape)

(4851, 17)

In [119]:
# Import the cleaned dataset into SQLite

df.to_sql(
    "ecommerce_sales",
    conn,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

Data imported successfully!

In [120]:
# Check how many rows are in the SQL table

result = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM ecommerce_sales",
    conn
)

result

   total_rows
0        4851

In [121]:
query = """
SELECT *
FROM ecommerce_sales
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1.0,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1.0,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1.0,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1.0,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1.0,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male
5,O100005,C15191,P214062,Beauty,53.91,0.10,2.0,Credit Card,2024-04-14,5,South,No,97.04,6.32,37.35,35,Female
6,O100006,C13772,P201363,Electronics,266.50,0.00,1.0,PayPal,2025-05-20,5,East,No,266.50,9.10,22.88,49,Male
7,O100007,C13092,P216691,Beauty,9.98,0.00,1.0,Credit Card,2023-09-14,4,West,No,9.98,4.51,-0.02,66,Other
8,O100008,C15734,P202751,Fashion,6.61,0.05,1.0,Debit Card,2023-10-23,6,West,No,6.28,3.43,-1.23,37,Female
9,O100009,C16265,P207782,Grocery,10.91,0.00,1.0,Credit Card,2023-10-31,6,South,No,10.91,2.76,-1.89,56,Male

In [122]:
query = """
SELECT order_id, category, price
FROM ecommerce_sales
WHERE price > 100;
"""

result = pd.read_sql(query, conn)

result

     order_id     category     price
0     O100000         Home  164.0800
1     O100002  Electronics  175.5800
2     O100006  Electronics  266.5000
3     O100018  Electronics  310.3575
4     O100022  Electronics  128.8000
...       ...          ...       ...
1514  O104842       Sports  154.1900
1515  O104844  Electronics  310.3575
1516  O104845      Fashion  142.4300
1517  O104848         Home  102.6600
1518  O104849  Electronics  152.4800

[1519 rows x 3 columns]

In [123]:
query = """
SELECT order_id, category, price
FROM ecommerce_sales
ORDER BY price DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

  order_id     category     price
0  O100018  Electronics  310.3575
1  O100024       Sports  310.3575
2  O100044  Electronics  310.3575
3  O100053  Electronics  310.3575
4  O100062  Electronics  310.3575
5  O100084  Electronics  310.3575
6  O100092  Electronics  310.3575
7  O100099  Electronics  310.3575
8  O100114  Electronics  310.3575
9  O100124  Electronics  310.3575

In [124]:
query = """
SELECT category, COUNT(*) AS order_count
FROM ecommerce_sales
GROUP BY category
ORDER BY order_count DESC;
"""

result = pd.read_sql(query, conn)

result

      category  order_count
0  Electronics          890
1      Fashion          885
2         Home          800
3      Grocery          596
4         Toys          580
5       Beauty          551
6       Sports          549

In [125]:
query = """
SELECT
    SUM(total_amount) AS total_sales,
    AVG(total_amount) AS average_order_value,
    MIN(total_amount) AS minimum_order_value,
    MAX(total_amount) AS maximum_order_value
FROM ecommerce_sales;
"""

result = pd.read_sql(query, conn)

result

   total_sales  average_order_value  minimum_order_value  maximum_order_value
0    566447.73            116.76927                 0.82               392.75

In [126]:
query = """
SELECT
    category,
    COUNT(*) AS order_count,
    AVG(total_amount) AS average_sales
FROM ecommerce_sales
GROUP BY category
HAVING COUNT(*) > 500
ORDER BY order_count DESC;
"""

result = pd.read_sql(query, conn)

result

      category  order_count  average_sales
0  Electronics          890     278.268652
1      Fashion          885      79.403345
2         Home          800     163.254000
3      Grocery          596      20.236628
4         Toys          580      30.090069
5       Beauty          551      37.938621
6       Sports          549     122.943570

In [127]:
query = """
CREATE TABLE IF NOT EXISTS category_summary AS
SELECT
    category,
    COUNT(*) AS order_count,
    SUM(total_amount) AS total_sales
FROM ecommerce_sales
GROUP BY category;
"""

conn.execute(query)
conn.commit()

print("category_summary table created!")

category_summary table created!

In [128]:
pd.read_sql("SELECT * FROM category_summary", conn)

      category  order_count  total_sales
0       Beauty          551     20904.18
1  Electronics          890    247659.10
2      Fashion          885     70271.96
3      Grocery          596     12061.03
4         Home          800    130603.20
5       Sports          549     67496.02
6         Toys          580     17452.24

In [129]:
query = """
SELECT
    e.order_id,
    e.category,
    e.total_amount,
    c.order_count,
    c.total_sales
FROM ecommerce_sales AS e
INNER JOIN category_summary AS c
    ON e.category = c.category
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

  order_id     category  total_amount  order_count  total_sales
0  O100000         Home        139.47          800    130603.20
1  O100001      Grocery         24.73          596     12061.03
2  O100002  Electronics        166.80          890    247659.10
3  O100003  Electronics         63.67          890    247659.10
4  O100004         Home         13.88          800    130603.20
5  O100005       Beauty         97.04          551     20904.18
6  O100006  Electronics        266.50          890    247659.10
7  O100007       Beauty          9.98          551     20904.18
8  O100008      Fashion          6.28          885     70271.96
9  O100009      Grocery         10.91          596     12061.03

In [130]:
query = """
SELECT
    e.order_id,
    e.category,
    e.total_amount,
    c.order_count,
    c.total_sales
FROM ecommerce_sales AS e
LEFT JOIN category_summary AS c
    ON e.category = c.category
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

  order_id     category  total_amount  order_count  total_sales
0  O100000         Home        139.47          800    130603.20
1  O100001      Grocery         24.73          596     12061.03
2  O100002  Electronics        166.80          890    247659.10
3  O100003  Electronics         63.67          890    247659.10
4  O100004         Home         13.88          800    130603.20
5  O100005       Beauty         97.04          551     20904.18
6  O100006  Electronics        266.50          890    247659.10
7  O100007       Beauty          9.98          551     20904.18
8  O100008      Fashion          6.28          885     70271.96
9  O100009      Grocery         10.91          596     12061.03

In [131]:
query = """
SELECT
    e.order_id,
    e.category,
    e.total_amount,
    c.order_count,
    c.total_sales
FROM ecommerce_sales AS e
LEFT JOIN category_summary AS c
    ON e.category = c.category
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

  order_id     category  total_amount  order_count  total_sales
0  O100000         Home        139.47          800    130603.20
1  O100001      Grocery         24.73          596     12061.03
2  O100002  Electronics        166.80          890    247659.10
3  O100003  Electronics         63.67          890    247659.10
4  O100004         Home         13.88          800    130603.20
5  O100005       Beauty         97.04          551     20904.18
6  O100006  Electronics        266.50          890    247659.10
7  O100007       Beauty          9.98          551     20904.18
8  O100008      Fashion          6.28          885     70271.96
9  O100009      Grocery         10.91          596     12061.03

In [132]:
query = """
SELECT
    order_id,
    category,
    total_amount
FROM ecommerce_sales
WHERE total_amount > (
    SELECT AVG(total_amount)
    FROM ecommerce_sales
)
ORDER BY total_amount DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

  order_id     category  total_amount
0  O100018  Electronics        392.75
1  O100024       Sports        392.75
2  O100051         Home        392.75
3  O100053  Electronics        392.75
4  O100057         Home        392.75
5  O100071      Fashion        392.75
6  O100084  Electronics        392.75
7  O100092  Electronics        392.75
8  O100099  Electronics        392.75
9  O100114  Electronics        392.75

In [133]:
query = """
WITH category_sales AS (
    SELECT
        category,
        SUM(total_amount) AS total_sales
    FROM ecommerce_sales
    GROUP BY category
)
SELECT
    category,
    total_sales
FROM category_sales
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, conn)

result

      category  total_sales
0  Electronics    247659.10
1         Home    130603.20
2      Fashion     70271.96
3       Sports     67496.02
4       Beauty     20904.18
5         Toys     17452.24
6      Grocery     12061.03

In [134]:
query = """
SELECT
    order_id,
    category,
    total_amount,
    ROW_NUMBER() OVER (
        PARTITION BY category
        ORDER BY total_amount DESC
    ) AS row_num
FROM ecommerce_sales
LIMIT 20;
"""

result = pd.read_sql(query, conn)

result

   order_id category  total_amount  row_num
0   O102009   Beauty        324.49        1
1   O102342   Beauty        264.52        2
2   O101293   Beauty        231.74        3
3   O100483   Beauty        212.19        4
4   O102734   Beauty        200.35        5
5   O102889   Beauty        198.05        6
6   O104608   Beauty        188.92        7
7   O100680   Beauty        178.85        8
8   O103723   Beauty        173.46        9
9   O100444   Beauty        171.86       10
10  O101739   Beauty        171.18       11
11  O104451   Beauty        169.85       12
12  O100322   Beauty        168.32       13
13  O100151   Beauty        158.85       14
14  O103196   Beauty        158.40       15
15  O103311   Beauty        155.09       16
16  O104497   Beauty        154.20       17
17  O103540   Beauty        153.65       18
18  O100931   Beauty        150.06       19
19  O103596   Beauty        149.10       20

In [135]:
query = """
SELECT
    order_id,
    category,
    total_amount,
    RANK() OVER (
        PARTITION BY category
        ORDER BY total_amount DESC
    ) AS rank_num
FROM ecommerce_sales
LIMIT 20;
"""

result = pd.read_sql(query, conn)

result

   order_id category  total_amount  rank_num
0   O102009   Beauty        324.49         1
1   O102342   Beauty        264.52         2
2   O101293   Beauty        231.74         3
3   O100483   Beauty        212.19         4
4   O102734   Beauty        200.35         5
5   O102889   Beauty        198.05         6
6   O104608   Beauty        188.92         7
7   O100680   Beauty        178.85         8
8   O103723   Beauty        173.46         9
9   O100444   Beauty        171.86        10
10  O101739   Beauty        171.18        11
11  O104451   Beauty        169.85        12
12  O100322   Beauty        168.32        13
13  O100151   Beauty        158.85        14
14  O103196   Beauty        158.40        15
15  O103311   Beauty        155.09        16
16  O104497   Beauty        154.20        17
17  O103540   Beauty        153.65        18
18  O100931   Beauty        150.06        19
19  O103596   Beauty        149.10        20

In [136]:
query = """
SELECT
    order_id,
    order_date,
    total_amount,
    LAG(total_amount) OVER (
        ORDER BY order_date
    ) AS previous_order_amount
FROM ecommerce_sales
LIMIT 20;
"""

result = pd.read_sql(query, conn)

result

   order_id  order_date  total_amount  previous_order_amount
0   O100096  2023-09-12          4.89                    NaN
1   O101207  2023-09-12         44.56                   4.89
2   O102009  2023-09-12        324.49                  44.56
3   O102271  2023-09-12         18.07                 324.49
4   O103242  2023-09-12        330.67                  18.07
5   O104338  2023-09-12        197.70                 330.67
6   O104424  2023-09-12         15.51                 197.70
7   O104739  2023-09-12          8.55                  15.51
8   O100840  2023-09-13          9.49                   8.55
9   O101494  2023-09-13         20.00                   9.49
10  O101751  2023-09-13         70.28                  20.00
11  O103077  2023-09-13         10.21                  70.28
12  O103694  2023-09-13        278.06                  10.21
13  O104411  2023-09-13         37.52                 278.06
14  O104638  2023-09-13        392.75                  37.52
15  O104640  2023-09-13        260.27                 392.75
16  O104642  2023-09-13        392.75                 260.27
17  O100007  2023-09-14          9.98                 392.75
18  O101595  2023-09-14        392.75                   9.98
19  O101830  2023-09-14          3.96                 392.75

In [137]:
query = """
SELECT
    order_id,
    order_date,
    total_amount,
    LEAD(total_amount) OVER (
        ORDER BY order_date
    ) AS next_order_amount
FROM ecommerce_sales
LIMIT 20;
"""

result = pd.read_sql(query, conn)

result

   order_id  order_date  total_amount  next_order_amount
0   O100096  2023-09-12          4.89              44.56
1   O101207  2023-09-12         44.56             324.49
2   O102009  2023-09-12        324.49              18.07
3   O102271  2023-09-12         18.07             330.67
4   O103242  2023-09-12        330.67             197.70
5   O104338  2023-09-12        197.70              15.51
6   O104424  2023-09-12         15.51               8.55
7   O104739  2023-09-12          8.55               9.49
8   O100840  2023-09-13          9.49              20.00
9   O101494  2023-09-13         20.00              70.28
10  O101751  2023-09-13         70.28              10.21
11  O103077  2023-09-13         10.21             278.06
12  O103694  2023-09-13        278.06              37.52
13  O104411  2023-09-13         37.52             392.75
14  O104638  2023-09-13        392.75             260.27
15  O104640  2023-09-13        260.27             392.75
16  O104642  2023-09-13        392.75               9.98
17  O100007  2023-09-14          9.98             392.75
18  O101595  2023-09-14        392.75               3.96
19  O101830  2023-09-14          3.96              25.84

In [138]:
query = """
SELECT
    strftime('%Y-%m', order_date) AS month,
    SUM(total_amount) AS monthly_sales
FROM ecommerce_sales
GROUP BY month
ORDER BY month;
"""

result = pd.read_sql(query, conn)

result

      month  monthly_sales
0   2023-09       14583.27
1   2023-10       24301.62
2   2023-11       20894.68
3   2023-12       28102.59
4   2024-01       20093.29
5   2024-02       20352.02
6   2024-03       23710.34
7   2024-04       23317.61
8   2024-05       26466.26
9   2024-06       19472.77
10  2024-07       20265.24
11  2024-08       23154.95
12  2024-09       20144.58
13  2024-10       24663.38
14  2024-11       22588.35
15  2024-12       24705.62
16  2025-01       21471.24
17  2025-02       24659.99
18  2025-03       24102.30
19  2025-04       24216.09
20  2025-05       28217.66
21  2025-06       23616.76
22  2025-07       27763.12
23  2025-08       26266.51
24  2025-09        9317.49

In [139]:
query = """
SELECT
    customer_id,
    SUM(total_amount) AS total_revenue
FROM ecommerce_sales
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

  customer_id  total_revenue
0      C14000        1034.45
1      C10574         952.46
2      C15203         918.36
3      C16164         857.94
4      C16949         846.37
5      C13291         841.88
6      C16530         834.13
7      C14583         812.63
8      C16295         810.86
9      C16344         810.64

In [140]:
query = """
WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(*) AS order_count
    FROM ecommerce_sales
    GROUP BY customer_id
)
SELECT
    COUNT(*) AS total_customers,
    SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) AS returning_customers,
    ROUND(
        100.0 * SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS retention_rate_percent
FROM customer_orders;
"""

result = pd.read_sql(query, conn)

result

   total_customers  returning_customers  retention_rate_percent
0             3582                 1027                   28.67

In [141]:
query = """
SELECT
    category,
    COUNT(*) AS total_orders,
    SUM(total_amount) AS total_sales,
    AVG(total_amount) AS average_order_value,
    AVG(profit_margin) AS average_profit_margin
FROM ecommerce_sales
GROUP BY category
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, conn)

result

,category,total_orders,total_sales,average_order_value,average_profit_margin
0,Electronics,890,247659.10,278.268652,37.619337
1,Home,800,130603.20,163.254000,36.078150
2,Fashion,885,70271.96,79.403345,20.328350
3,Sports,549,67496.02,122.943570,28.475738
4,Beauty,551,20904.18,37.938621,12.085082
5,Toys,580,17452.24,30.090069,7.483310
6,Grocery,596,12061.03,20.236628,-2.257651

In [142]:
query = """
SELECT
    order_date,
    total_amount,
    AVG(total_amount) OVER (
        ORDER BY order_date
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS moving_avg_7_orders,
    SUM(total_amount) OVER (
        ORDER BY order_date
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS cumulative_sales
FROM ecommerce_sales
ORDER BY order_date
LIMIT 20;
"""

result = pd.read_sql(query, conn)

result

    order_date  total_amount  moving_avg_7_orders  cumulative_sales
0   2023-09-12          4.89             4.890000              4.89
1   2023-09-12         44.56            24.725000             49.45
2   2023-09-12        324.49           124.646667            373.94
3   2023-09-12         18.07            98.002500            392.01
4   2023-09-12        330.67           144.536000            722.68
5   2023-09-12        197.70           153.396667            920.38
6   2023-09-12         15.51           133.698571            935.89
7   2023-09-12          8.55           134.221429            944.44
8   2023-09-13          9.49           129.211429            953.93
9   2023-09-13         20.00            85.712857            973.93
10  2023-09-13         70.28            93.171429           1044.21
11  2023-09-13         10.21            47.391429           1054.42
12  2023-09-13        278.06            58.871429           1332.48
13  2023-09-13         37.52            62.015714           1370.00
14  2023-09-13        392.75           116.901429           1762.75
15  2023-09-13        260.27           152.727143           2023.02
16  2023-09-13        392.75           205.977143           2415.77
17  2023-09-14          9.98           197.362857           2425.75
18  2023-09-14        392.75           252.011429           2818.50
19  2023-09-14          3.96           212.854286           2822.46

In [143]:
query = """
SELECT
    order_date,
    total_amount,
    AVG(total_amount) OVER (
        ORDER BY order_date
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS moving_avg_7_orders,
    SUM(total_amount) OVER (
        ORDER BY order_date
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS cumulative_sales
FROM ecommerce_sales
ORDER BY order_date
LIMIT 20;
"""

result = pd.read_sql(query, conn)

result

    order_date  total_amount  moving_avg_7_orders  cumulative_sales
0   2023-09-12          4.89             4.890000              4.89
1   2023-09-12         44.56            24.725000             49.45
2   2023-09-12        324.49           124.646667            373.94
3   2023-09-12         18.07            98.002500            392.01
4   2023-09-12        330.67           144.536000            722.68
5   2023-09-12        197.70           153.396667            920.38
6   2023-09-12         15.51           133.698571            935.89
7   2023-09-12          8.55           134.221429            944.44
8   2023-09-13          9.49           129.211429            953.93
9   2023-09-13         20.00            85.712857            973.93
10  2023-09-13         70.28            93.171429           1044.21
11  2023-09-13         10.21            47.391429           1054.42
12  2023-09-13        278.06            58.871429           1332.48
13  2023-09-13         37.52            62.015714           1370.00
14  2023-09-13        392.75           116.901429           1762.75
15  2023-09-13        260.27           152.727143           2023.02
16  2023-09-13        392.75           205.977143           2415.77
17  2023-09-14          9.98           197.362857           2425.75
18  2023-09-14        392.75           252.011429           2818.50
19  2023-09-14          3.96           212.854286           2822.46

In [144]:
query = """
CREATE VIEW IF NOT EXISTS category_sales_view AS
SELECT
    category,
    COUNT(*) AS total_orders,
    SUM(total_amount) AS total_sales,
    AVG(total_amount) AS average_order_value
FROM ecommerce_sales
GROUP BY category;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

In [145]:
query = """
CREATE VIEW IF NOT EXISTS category_sales_view AS
SELECT
    category,
    COUNT(*) AS total_orders,
    SUM(total_amount) AS total_sales,
    AVG(total_amount) AS average_order_value
FROM ecommerce_sales
GROUP BY category;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

In [146]:
result = pd.read_sql(
    "SELECT * FROM category_sales_view;",
    conn
)

result

      category  total_orders  total_sales  average_order_value
0       Beauty           551     20904.18            37.938621
1  Electronics           890    247659.10           278.268652
2      Fashion           885     70271.96            79.403345
3      Grocery           596     12061.03            20.236628
4         Home           800    130603.20           163.254000
5       Sports           549     67496.02           122.943570
6         Toys           580     17452.24            30.090069

In [147]:
query = """
EXPLAIN QUERY PLAN
SELECT
    category,
    SUM(total_amount) AS total_sales
FROM ecommerce_sales
GROUP BY category;
"""

result = pd.read_sql(query, conn)

result

   id  parent  notused                        detail
0   6       0      216          SCAN ecommerce_sales
1   8       0        0  USE TEMP B-TREE FOR GROUP BY

In [148]:
query = """
CREATE INDEX IF NOT EXISTS idx_category
ON ecommerce_sales(category);
"""

conn.execute(query)
conn.commit()

print("Index created successfully!")

Index created successfully!

In [149]:
result = pd.read_sql(
    "PRAGMA index_list('ecommerce_sales');",
    conn
)

result

   seq          name  unique origin  partial
0    0  idx_category       0      c        0

In [150]:
import sqlite3


def get_connection():
    conn = sqlite3.connect("ecommerce_sales.db")
    return conn


if __name__ == "__main__":
    conn = get_connection()
    print("Database connected successfully!")
    conn.close()

Database connected successfully!

In [151]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("ecommerce_sales.db")

print("Database connected successfully!")

Database connected successfully!

In [152]:
import sqlite3


def get_connection():
    conn = sqlite3.connect("ecommerce_sales.db")
    return conn


if __name__ == "__main__":
    conn = get_connection()
    print("Database connected successfully!")
    conn.close()

Database connected successfully!

In [153]:
import sqlite3


def get_connection():
    return sqlite3.connect("ecommerce_sales.db")

In [156]:
import importlib
import scripts.db_utils as db_utils

importlib.reload(db_utils)

print(hasattr(db_utils, "get_connection"))

False

In [157]:
import scripts.db_utils as db_utils

print(db_utils.__file__)
print(dir(db_utils))

C:\Users\DELL\Desktop\apexplanet-data-analytics\scripts\db_utils.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

In [158]:
import sqlite3

conn = sqlite3.connect("ecommerce_sales.db")

print("Database connected successfully!")

Database connected successfully!

In [159]:
query = """
SELECT COUNT(*) AS total_records
FROM ecommerce_sales;
"""

result = pd.read_sql(query, conn)

result

   total_records
0           4851

In [161]:
import scripts.db_utils as db_utils

print(db_utils.__file__)
print(db_utils.__dict__.keys())

C:\Users\DELL\Desktop\apexplanet-data-analytics\scripts\db_utils.py
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__'])

In [163]:
import sqlite3

def get_connection():
    conn = sqlite3.connect("ecommerce_sales.db")
    return conn

In [164]:
with open("scripts/db_utils.py", "r") as f:
    print(f.read())

In [165]:
code = '''import sqlite3

def get_connection():
    conn = sqlite3.connect("ecommerce_sales.db")
    return conn
'''

with open("scripts/db_utils.py", "w") as f:
    f.write(code)

print("db_utils.py updated successfully!")

db_utils.py updated successfully!

In [166]:
import importlib
import scripts.db_utils as db_utils

importlib.reload(db_utils)

print(hasattr(db_utils, "get_connection"))

True

In [167]:
import importlib
import scripts.db_utils as db_utils

importlib.reload(db_utils)

conn = db_utils.get_connection()

print("Connection successful!")

Connection successful!